### ISSUE TITLE
Exclude tags from running GitHub Actions workflows

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/sapphire#57]
Add this to prevent tag pushes from running my workflow:

```
on:
  push:
    tags-ignore:
      - '**'
```

Full documentation at:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
